service: driver-app-api
provider:
  apiGateway:
    binaryMediaTypes:
      - 'multipart/form-data'
  name: aws	
  iam:
    role:
      statements:
        # Allow functions to list all buckets
        - Effect: Allow
          Action: 's3:*'
          Resource: '*'
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
  memorySize: 1024
  timeout: 30
functions:
  app:
    handler: app/app.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
